name: dpip
description: Disaster Prevention Information Platform
publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^2.1.0
  animations: ^2.0.11
  app_settings: ^5.1.1
  dio: ^5.4.1
  firebase_messaging: ^14.6.8
  firebase_core: ^2.22.0
  flutter_markdown: ^0.6.20+1
  flutter_local_notifications: ^16.3.2
  hooks_riverpod: ^2.4.10
  latlong2: ^0.9.0
  native_shared_preferences: ^2.0.9
  package_info_plus: ^5.0.1
  permission_handler: ^11.3.0
  url_launcher: ^6.2.1
  intl: ^0.19.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true